# Generated by Django 5.0.6 on 2025-06-21 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patienthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patienthistory',
            options={'get_latest_by': 'performed_at', 'ordering': ['-performed_at'], 'verbose_name': 'Historique patient', 'verbose_name_plural': 'Historiques patients'},
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(default='Cameroun', max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Contact d'urgence - Nom"),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Contact d'urgence - Téléphone"),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lien avec le patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history',
            field=models.TextField(blank=True, help_text='Maladies héréditaires ou fréquentes dans la famille', null=True, verbose_name='Antécédents familiaux'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_synced',
            field=models.BooleanField(default=False, help_text='Indique si le dossier a été synchronisé avec le serveur central', verbose_name='Synchronisé'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_consultation',
            field=models.DateField(blank=True, null=True, verbose_name='Dernière consultation'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_patients', to=settings.AUTH_USER_MODEL, verbose_name='Dernière modification par'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, help_text='Antécédents chirurgicaux, hospitalisations, etc.', null=True, verbose_name='Antécédents médicaux'),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_appointment',
            field=models.DateField(blank=True, null=True, verbose_name='Prochain rendez-vous'),
        ),
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, help_text='Informations complémentaires', null=True, verbose_name='Notes supplémentaires'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_alt',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone secondaire'),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('deceased', 'Décédé')], default='active', max_length=10, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sync_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de synchronisation'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sync_errors',
            field=models.TextField(blank=True, null=True, verbose_name='Erreurs de synchronisation'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sync_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Statut de synchronisation'),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='changes',
            field=models.JSONField(blank=True, help_text='Détail des champs modifiés', null=True, verbose_name='Modifications'),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='Navigateur'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='Liste des allergies médicamenteuses ou alimentaires', null=True, verbose_name='Allergies connues'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Groupe sanguin'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='chronic_diseases',
            field=models.TextField(blank=True, help_text='Antécédents médicaux importants', null=True, verbose_name='Maladies chroniques'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='current_medications',
            field=models.TextField(blank=True, help_text='Médicaments actuels et posologie', null=True, verbose_name='Traitements en cours'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_id',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Numéro dossier médical'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro CNI'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='region',
            field=models.CharField(blank=True, choices=[('AD', 'Adamaoua'), ('CE', 'Centre'), ('EN', 'Extrême-Nord'), ('ES', 'Est'), ('LT', 'Littoral'), ('NO', 'Nord'), ('NW', 'Nord-Ouest'), ('OU', 'Ouest'), ('SU', 'Sud'), ('SW', 'Sud-Ouest')], db_index=True, max_length=2, null=True, verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='action',
            field=models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('read', 'Consultation'), ('export', 'Exportation'), ('import', 'Importation'), ('merge', 'Fusion'), ('restore', 'Restauration')], db_index=True, max_length=10, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='patients.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='performed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date/heure'),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_history_actions', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par'),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='snapshot',
            field=models.JSONField(help_text="État du patient au moment de l'action", verbose_name='Instantané'),
        ),
    ]
