# Generated by Django 5.0.6 on 2025-06-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patienthistory_options_patient_city_and_more'),
    ]

    operations = [
    ]
