# Generated by Django 5.0.6 on 2025-06-21 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_enhance_patient_models_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patienthistory',
            options={},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='city',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='country',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact_relation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='family_history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_synced',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_consultation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='next_appointment',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone_alt',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sync_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sync_errors',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sync_status',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='changes',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='user_agent',
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='chronic_diseases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='current_medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='action',
            field=models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='performed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='snapshot',
            field=models.JSONField(),
        ),
    ]
