# Generated by Django 5.0.6 on 2025-06-21 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patienthistory_options_remove_patient_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('view', 'Consultation'), ('create', 'Création'), ('update', 'Mise à jour'), ('delete', 'Suppression')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='patients.patient')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal des accès patient',
                'verbose_name_plural': 'Journaux des accès patients',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['patient', 'user', 'timestamp'], name='patients_pa_patient_ca9d5f_idx'), models.Index(fields=['timestamp'], name='patients_pa_timesta_1ff3e9_idx')],
            },
        ),
    ]
