# Generated by Django 4.2.23 on 2025-06-22 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0006_patientaccesslog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PatientAccessLog",
        ),
    ]
