# Generated by Django 5.0.6 on 2025-06-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationrequest',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
