# Generated by Django 5.0.6 on 2025-06-15 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userregistrationrequest_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'custom permission',
                'verbose_name_plural': 'custom permissions',
            },
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'verbose_name': 'role permission', 'verbose_name_plural': 'role permissions'},
        ),
        migrations.AlterModelOptions(
            name='subrolepermission',
            options={'verbose_name': 'permission de sous-rôle', 'verbose_name_plural': 'permissions de sous-rôles'},
        ),
        migrations.AlterField(
            model_name='subrolepermission',
            name='sub_role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('doctor', 'Médecin'), ('nurse', 'Infirmier(ère)'), ('patient', 'Patient(e)'), ('lab_technician', 'Technicien(ne) de laboratoire'), ('pharmacist', 'Pharmacien(ne)'), ('receptionist', 'Réceptionniste'), ('accountant', 'Comptable')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='authentication.custompermission'),
        ),
        migrations.AlterField(
            model_name='subrolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrole_permissions', to='authentication.custompermission'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
