# Generated by Django 5.0.6 on 2025-06-15 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_custompermission_alter_rolepermission_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
            },
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'verbose_name': 'permission de rôle', 'verbose_name_plural': 'permissions de rôle'},
        ),
        migrations.AlterModelOptions(
            name='subrolepermission',
            options={'ordering': ['role', 'sub_role', 'permission']},
        ),
        migrations.AlterField(
            model_name='subrolepermission',
            name='sub_role',
            field=models.CharField(choices=[('GENERAL_PRACTITIONER', 'Médecin Généraliste'), ('CARDIOLOGIST', 'Cardiologue'), ('DIABETOLOGIST', 'Diabétologue'), ('NEUROLOGIST', 'Neurologue'), ('PEDIATRICIAN', 'Pédiatre'), ('RADIOLOGIST', 'Radiologue'), ('IMAGING_TECHNICIAN', 'Technicien en Imagerie'), ('LAB_TECHNICIAN', 'Technicien de Laboratoire')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='authentication.permission'),
        ),
        migrations.AlterField(
            model_name='subrolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrole_permissions', to='authentication.permission'),
        ),
        migrations.DeleteModel(
            name='CustomPermission',
        ),
    ]
