# Generated by Django 5.2.1 on 2025-06-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='prevention_details',
            field=models.TextField(blank=True, verbose_name='Détails de prévention'),
        ),
        migrations.AddField(
            model_name='disease',
            name='useful_links',
            field=models.TextField(blank=True, verbose_name='Liens utiles'),
        ),
        migrations.AddField(
            model_name='disease',
            name='when_to_see_doctor',
            field=models.TextField(blank=True, verbose_name='Quand consulter un médecin'),
        ),
    ]
