# Generated by Django 4.2.23 on 2025-06-26 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imaging.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0007_delete_patientaccesslog"),
    ]

    operations = [
        migrations.CreateModel(
            name="DicomStudy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("study_instance_uid", models.CharField(max_length=100, unique=True)),
                ("study_date", models.DateField(default=django.utils.timezone.now)),
                ("study_time", models.TimeField(default=django.utils.timezone.now)),
                (
                    "study_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("modality", models.CharField(max_length=50)),
                ("orthanc_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Téléchargé"),
                            ("PENDING", "En attente d'analyse"),
                            ("ANALYZED", "Analysé"),
                            ("REPORTED", "Rapport disponible"),
                        ],
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medical_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dicom_studies",
                        to="patients.medicalrecord",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dicom_studies",
                        to="patients.patient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_studies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Étude DICOM",
                "verbose_name_plural": "Études DICOM",
                "ordering": ["-study_date", "-study_time"],
            },
        ),
        migrations.CreateModel(
            name="RadiologyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("findings", models.TextField()),
                ("impression", models.TextField()),
                ("recommendations", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("PRELIMINARY", "Préliminaire"),
                            ("FINAL", "Final"),
                            ("AMENDED", "Modifié"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "radiologist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="radiology_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="imaging.dicomstudy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport de radiologie",
                "verbose_name_plural": "Rapports de radiologie",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DicomSeries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("series_instance_uid", models.CharField(max_length=100, unique=True)),
                ("series_number", models.IntegerField()),
                (
                    "series_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("body_part", models.CharField(blank=True, max_length=100, null=True)),
                ("orthanc_id", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="imaging.dicomstudy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Série DICOM",
                "verbose_name_plural": "Séries DICOM",
                "ordering": ["series_number"],
            },
        ),
        migrations.CreateModel(
            name="DicomInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sop_instance_uid", models.CharField(max_length=100, unique=True)),
                ("instance_number", models.IntegerField()),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to=imaging.models.dicom_file_path
                    ),
                ),
                ("orthanc_id", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="imaging.dicomseries",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instance DICOM",
                "verbose_name_plural": "Instances DICOM",
                "ordering": ["instance_number"],
            },
        ),
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("target_type", models.CharField(max_length=100)),
                ("target_id", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Succès"), ("FAIL", "Échec")],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log d'action",
                "verbose_name_plural": "Logs d'action",
                "db_table": "imaging_action_logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
