# Generated by Django 5.0.6 on 2025-06-15 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
    ]
