# Generated by Django 5.0.6 on 2025-06-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotknowledgebase',
            name='category',
            field=models.CharField(choices=[('DISEASE', 'Maladie'), ('SYMPTOM', 'Symptôme'), ('MEDICATION', 'Médicament'), ('PROCEDURE', 'Procédure médicale'), ('FIRST_AID', 'Premiers secours'), ('NUTRITION', 'Nutrition'), ('PREVENTION', 'Prévention'), ('GENERAL', 'Information générale'), ('MEDICAL_PROCEDURE', 'Procédure médicale avancée'), ('DIAGNOSTIC', 'Aide au diagnostic'), ('TREATMENT', 'Traitement et prescription'), ('PROTOCOL', 'Protocole médical'), ('EQUIPMENT', 'Utilisation des équipements'), ('EMERGENCY', "Procédure d'urgence")], max_length=30),
        ),
    ]
