# Generated by Django 5.0.6 on 2025-06-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chatbotknowledgebase_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='session_type',
            field=models.CharField(choices=[('GENERAL', 'Général'), ('MEDICAL', 'Médical'), ('TECHNICAL', 'Technique'), ('ADMIN', 'Administratif')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chatbotknowledgebase',
            name='category',
            field=models.CharField(choices=[('DISEASE', 'Maladie'), ('SYMPTOM', 'Symptôme'), ('MEDICATION', 'Médicament'), ('PROCEDURE', 'Procédure médicale'), ('FIRST_AID', 'Premiers secours'), ('NUTRITION', 'Nutrition'), ('PREVENTION', 'Prévention'), ('GENERAL', 'Information générale')], max_length=20),
        ),
    ]
