# Generated by Django 5.0.6 on 2025-06-04 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('model_type', models.CharField(choices=[('CLASSIFICATION', 'Classification'), ('REGRESSION', 'Régression'), ('ANOMALY', "Détection d'anomalies"), ('SEGMENTATION', "Segmentation d'image")], max_length=20)),
                ('description', models.TextField()),
                ('target_disease', models.CharField(max_length=100)),
                ('accuracy', models.FloatField()),
                ('status', models.CharField(choices=[('DEVELOPMENT', 'En développement'), ('TESTING', 'En test'), ('PRODUCTION', 'En production'), ('DEPRECATED', 'Déprécié')], max_length=20)),
                ('training_date', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modèle IA',
                'verbose_name_plural': 'Modèles IA',
                'ordering': ['name', '-version'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction_result', models.TextField()),
                ('confidence_score', models.FloatField()),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Élevée'), ('CRITICAL', 'Critique')], max_length=10)),
                ('requires_attention', models.BooleanField(default=False)),
                ('input_data', models.JSONField(help_text='Données utilisées pour la prédiction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_predictions', to=settings.AUTH_USER_MODEL)),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_predictions', to='patients.medicalrecord')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predictions', to='ai_diagnostic.aimodel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_predictions', to='patients.patient')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prédiction IA',
                'verbose_name_plural': 'Prédictions IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('ANOMALY', 'Anomalie détectée'), ('CRITICAL', 'Valeur critique'), ('TREND', 'Tendance inquiétante'), ('INTERACTION', 'Interaction médicamenteuse')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('VIEWED', 'Vue'), ('ACKNOWLEDGED', 'Confirmée'), ('RESOLVED', 'Résolue'), ('DISMISSED', 'Ignorée')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='ai_diagnostic.aiprediction')),
            ],
            options={
                'verbose_name': 'Alerte IA',
                'verbose_name_plural': 'Alertes IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
