# Generated by Django 5.2.1 on 2025-06-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_diagnostic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aialert',
            name='related_data',
            field=models.JSONField(blank=True, default=dict, help_text="Données supplémentaires liées à l'alerte (valeurs, seuils, etc.)"),
        ),
    ]
