# Generated by Django 5.2.1 on 2025-06-20 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_diagnostic', '0002_aialert_related_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aialert',
            name='related_data',
        ),
    ]
