# Generated by Django 5.0.6 on 2025-06-21 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ai_diagnostic', '0003_remove_aialert_related_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
