# Generated by Django 4.2.23 on 2025-06-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_diagnostic", "0004_add_created_at_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("DEVELOPMENT", "En développement"),
                    ("TESTING", "En test"),
                    ("PRODUCTION", "En production"),
                    ("DEPRECATED", "Déprécié"),
                ],
                default="DEVELOPMENT",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="aimodel",
            table="ai_diagnostic_models",
        ),
    ]
