# Generated by Django 4.2.23 on 2025-06-22 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blood_donation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bloodcenter",
            table="blood_donation_blood_center",
        ),
    ]
