# Generated by Django 5.2.1 on 2025-06-11 23:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0002_remove_bloodbankcenter_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbankcenter',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='bloodbankcenter',
            name='longitude',
        ),
        migrations.AddField(
            model_name='bloodbankcenter',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
