# Generated by Django 4.2.23 on 2025-06-22 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blood_bank", "0003_remove_bloodbankcenter_latitude_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bloodbankcenter",
            options={
                "ordering": ["name"],
                "verbose_name": "Centre de transfusion sanguine",
                "verbose_name_plural": "Centres de transfusion sanguine",
            },
        ),
        migrations.AddField(
            model_name="bloodbankcenter",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="bloodbankcenter",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_blood_banks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="bloodbankcenter",
            table="blood_bank_centers",
        ),
    ]
